version: 0.2

phases:
  pre_build:
    runtime-versions:
      nodejs: 10
    commands:
      # Install dependencies needed for running tests
      - npm install
  build:  
      commands:  
        - npm start
